# Generated by Django 5.2.15 on 2026-06-15 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('plant_name', models.CharField(max_length=100)),
                ('disease_name', models.CharField(max_length=150)),
                ('confidence', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('natural_remedies', models.TextField(blank=True)),
                ('chemical_remedies', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
