import os
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER


def generate_pdf_report(history):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#2d5a27'),
        alignment=TA_CENTER,
        spaceAfter=10,
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2d5a27'),
        spaceBefore=15,
        spaceAfter=5,
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        textColor=colors.HexColor('#333333'),
    )

    story = []

    story.append(Paragraph("🌿 AI Plant Doctor", title_style))
    story.append(Paragraph("Plant Disease Analysis Report", styles['Heading3']))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#2d5a27')))
    story.append(Spacer(1, 0.5 * cm))

    if history.image and os.path.exists(history.image.path):
        img = Image(history.image.path, width=8 * cm, height=6 * cm)
        img.hAlign = 'CENTER'
        story.append(img)
        story.append(Spacer(1, 0.3 * cm))

    confidence_str = f"{history.confidence:.1f}%"
    status_text = "✅ Healthy" if history.is_healthy else "⚠️ Disease Detected"

    summary_data = [
        ['Plant', history.plant_name],
        ['Disease', history.disease_name],
        ['Confidence', confidence_str],
        ['Status', status_text],
        ['Date Analyzed', history.created_at.strftime('%B %d, %Y at %I:%M %p')],
    ]

    summary_table = Table(summary_data, colWidths=[4 * cm, 12 * cm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#2d5a27')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (1, 0), (1, -1), colors.HexColor('#f0f7f0')),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ('ROWBACKGROUNDS', (1, 0), (1, -1), [colors.HexColor('#f0f7f0'), colors.white]),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))

    story.append(summary_table)
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cccccc')))

    def add_section(title, content):
        if content:
            story.append(Paragraph(title, heading_style))
            story.append(Paragraph(content, body_style))

    is_healthy = history.is_healthy
    add_section("📋 Health Status" if is_healthy else "📋 Disease Description", history.description)
    add_section("🔬 Growth Factors" if is_healthy else "🔬 Causes", history.causes)
    add_section("👁️ Healthy Signs" if is_healthy else "👁️ Symptoms", history.symptoms)
    add_section("🌱 Organic Care & Growth Boosters" if is_healthy else "🌱 Natural Remedies", history.natural_remedies)
    add_section("💊 Nutrients & Maintenance" if is_healthy else "💊 Chemical Remedies", history.chemical_remedies)
    add_section("🛡️ Protection & Prevention" if is_healthy else "🛡️ Prevention Tips", history.prevention)

    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#2d5a27')))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=9,
                                   textColor=colors.grey, alignment=TA_CENTER)
    story.append(Paragraph(
        f"Generated by AI Plant Doctor | {datetime.now().strftime('%B %d, %Y')} | Analyzed by: {history.user.username}",
        footer_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer
